# 验证码的保存时间
MAX_IMAGE_CODE_LIVE_TIME=300

# 短信验证码的有效期5分钟
SMS_CODE_REDIS_EXPIRES=300

# 短信的验证码的发送间隔1min
SEND_SMS_CODE_INTERVAL=60

# 短信验证码的模板
SMS_CODE_TEMP_ID=1

# access_token的有效期
ACCESS_TOKEN_LIFE_TIME=300
# qq登录的jwt token有效期
SAVE_QQ_USER_TOKEN_EXPIRES=300

# 邮件验证的有效期
VERIFY_EMAIL_TOKEN_EXPIRES=60*60*24

# 默认的地址
USER_ADDRESS_COUNTS_LIMIT=20
# 用户的历史记录
USER_BROWSING_HISTORY_COUNTS_LIMIT=5